app.host.authentication.service = http://app.indbank.security.auth

app.url.authentication.service.session_attributes = /api/v1/sessions?action=getSessionInfo
app.url.authentication.service.logoff = /api/security/rest-sts/logout
app.url.authentication.service.oauth_token = /v1/oauth/access_token
app.url.authentication.service.oauth_introspect = /v1/oauth/introspect


sessionInfo.clientId = 67h54567af2lvb96g
sessionInfo.clientSecret = 549ddsthsl3497hdace21zqajk5609

sessionInfo.all.clientId = 348jgrp832l1049btom
sessionInfo.all.clientSecret = uiQda4i3okh097hnk12yixzj6792cjlf

oauth.pdp.clientId = emergency-dummy-clientId
oauth.pdp.clientSecret = 1q2w3e4r
