spring:
  application:
    name: PolicyDecisionPointService

  datasource:
    url: jdbc:mysql://localhost:3306/AuthenticationDB
    username: root
    password: SM231198
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000

  mvc:
    async:
      request-timeout: 300000

server:
  port: 5059

  tomcat:
    connection-timeout: 300000
    keep-alive-timeout: 300000
    max-keep-alive-requests: 1000

    threads:
      max: 300
      min-spare: 50

    acceptor-thread-count: 2
    max-connections: 20000
    accept-count: 200

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.client: DEBUG
    org.apache.hc.client5.http: DEBUG
    io.github.resilience4j: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always
      show-components: always

  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      authenticationService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 120s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        pdpService:
          register-health-indicator: true
          sliding-window-type: COUNT_BASED
          sliding-window-size: 10
          minimum-number-of-calls: 10
          failure-rate-threshold: 50
          wait-duration-in-open-state: 120s
          permitted-number-of-calls-in-half-open-state: 5
          automatic-transition-from-open-to-half-open-enabled: true
          record-exceptions:
            - org.springframework.web.client.ResourceAccessException
            - org.springframework.web.client.HttpServerErrorException
            - java.net.ConnectException
            - java.net.SocketTimeoutException
